version: '3'
services:
  chat_server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000" # Adjust the port as needed
    environment:
      - ENV=production
      - SERVER_NODE
