services:
  chat_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Adjust the port as needed
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
