services:

  chat_server_development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - CHAT_SERVER_PORT=8080
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
