name: chat_server CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: '24.0'
        rebar3-version: '3.14'
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run coverage
      run: rebar3 cover
    - name: Archive coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: _build/test/cover/index.html
